import 'server-only';
import {
  Document,
  HeadingLevel,
  LevelFormat,
  Packer,
  Paragraph,
  TextRun,
} from 'docx';
import { markdownToDocxBlocks } from './markdownToDocx';
import type { ProjectDoc, SectionDoc } from '@/types/project';

export interface BuildDocxInput {
  project: ProjectDoc;
  sections: SectionDoc[];
  projectTypeName: string;
}

/**
 * Builds a Word document from the project + its ready sections.
 * Returns a Buffer ready to upload to Cloud Storage.
 */
export async function buildProjectDocx(input: BuildDocxInput): Promise<Buffer> {
  const { project, sections, projectTypeName } = input;

  const cover: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: project.title, bold: true })],
      spacing: { after: 240 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: projectTypeName,
          italics: true,
          color: '6B7280',
        }),
      ],
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by Xanthix.ai · ' +
            new Date().toLocaleDateString(project.outputLanguage === 'auto' ? 'en' : project.outputLanguage, {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            }),
          color: '9CA3AF',
          size: 18,
        }),
      ],
      spacing: { after: 360 },
    }),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: project.outputLanguage === 'tr' ? 'Proje Fikri' : 'Project Idea' })],
      spacing: { before: 120, after: 120 },
    }),
    new Paragraph({
      children: [new TextRun({ text: project.idea })],
      spacing: { after: 240 },
    }),
  ];

  const body: (Paragraph | ReturnType<typeof markdownToDocxBlocks>[number])[] = [];
  const ordered = [...sections].sort((a, b) => a.order - b.order);
  for (const [idx, section] of ordered.entries()) {
    if (section.status !== 'ready') continue;
    body.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [
          new TextRun({ text: `${idx + 1}. ${section.title}`, bold: true }),
        ],
        pageBreakBefore: idx > 0,
        spacing: { before: 360, after: 200 },
      }),
    );
    body.push(...markdownToDocxBlocks(section.content));
  }

  const doc = new Document({
    creator: 'Xanthix.ai',
    title: project.title,
    description: `${projectTypeName} application draft`,
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
          paragraph: { spacing: { line: 300 } },
        },
      },
    },
    numbering: {
      config: [
        {
          reference: 'numbered',
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: '%1.',
              alignment: 'left',
              style: { paragraph: { indent: { left: 360, hanging: 240 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 },
          },
        },
        children: [...cover, ...body],
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
